services:
  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net

  spark-worker-1:
    image: bitnami/spark:3.5.0
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=5
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-worker-2:
    image: bitnami/spark:3.5.0
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=5
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
    networks:
      - spark-net

  jupyter:
    image: jupyter/pyspark-notebook:python-3.11
    container_name: jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
